language: chsarp
mono: none
dist: xenial
dotnet: 3.1
addons:
 ssh_known_hosts: 91.166.139.178
 apt:
    packages:
    - sshpass
services:
- docker
install:
- cd ./CashManager
- dotnet restore ./CashManager/CashManager.csproj
- dotnet restore ./CashManagerTests/CashManagerTests.csproj
script:
- dotnet build ./CashManager/CashManager.csproj
- dotnet test CashManagerTests/CashManagerTests.csproj
after_success:
- cd ./Nginx
- docker-compose build
- docker tag nginx_cashmanager lucasboisbourdin/nginx_cashmanager_app
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin
- docker push lucasboisbourdin/nginx_cashmanager_app
before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- sshpass -p "$LUCAS_PASSWORD" ssh -o StrictHostKeyChecking=no lucas@91.166.139.178 cd Documents && touch helloimtravis
#- ssh -i /tmp/deploy_rsa lucas@91.166.139.178 cd Documents && touch helloimtravis
#- sudo sshpass -p "$LUCAS_PASSWORD" ssh -i /tmp/deploy_rsa lucas@91.166.139.178