language: chsarp
mono: none
dist: xenial
dotnet: 3.1
install:
  - cd ./CashManager
  - dotnet restore ./CashManager/CashManager.csproj
  - dotnet restore ./CashManagerTests/CashManagerTests.csproj
script:
  - dotnet build
  - dotnet test CashManagerTests/CashManagerTests.csproj
#services:
#  - docker
# before_install:
#   - docker-compose build
# after_success:
#   - docker images
#   - docker tag piscine_epitech_phoenix lucasboisbourdin/timemanager_phoenix
#   - docker tag piscine_epitech_vuejs lucasboisbourdin/timemanager_vuejs
#   - docker images
#   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin
#   - docker push lucasboisbourdin/timemanager_phoenix
#   - docker push lucasboisbourdin/timemanager_vuejs