language: chsarp
mono: none
dist: xenial
dotnet: 3.1
services:
- docker
install:
- cd ./CashManager
- dotnet restore ./CashManager/CashManager.csproj
- dotnet restore ./CashManagerTests/CashManagerTests.csproj
script:
- dotnet build ./CashManager/CashManager.csproj
- dotnet test CashManagerTests/CashManagerTests.csproj
after_success:
- cd ./Nginx
- docker-compose build
- docker images
before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- ssh -i /tmp/deploy_rsa root@91.166.139.178