version: '3.4'

services:
  cashmanager:
    image: ${DOCKER_REGISTRY-}cashmanager
    build:
      context: .
      dockerfile: CashManager/Dockerfile
    depends_on: 
        - db
  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=1Secure*Password1
